services:
  - type: web
    name: agent-ia-statistiques-backend
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn config.wsgi:application --bind 0.0.0.0:$PORT
    releaseCommand: python manage.py migrate --fake-initial && python manage.py collectstatic --noinput
    envVars:
      - key: DJANGO_SECRET_KEY
      - key: DJANGO_DEBUG
      - key: DJANGO_ALLOWED_HOSTS
      - key: DATABASE_URL
